spring:
  datasource:
    url: jdbc:postgresql://localhost:[PORT]/[DATABASE]
    driver-class-name: org.postgresql.Driver
    username:
    password:
  liquibase:
    change-log: classpath:/db/changelog-master.yaml

logging:
  file:
    name: log/logs.log

server:
  servlet:
    context-path: /ref-backend
